// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3HO5OZjuBaLssEVsfXXnSrrCx_DIGWqU',
    appId: '1:27868235925:web:77c66d861bb09ac957f39c',
    messagingSenderId: '27868235925',
    projectId: 'firstflutterapp-4ddae',
    authDomain: 'firstflutterapp-4ddae.firebaseapp.com',
    storageBucket: 'firstflutterapp-4ddae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg-ztdOnk7xJ8Q4DY20ZYEpjUiLEl3OhQ',
    appId: '1:27868235925:android:242408778e7f3d3557f39c',
    messagingSenderId: '27868235925',
    projectId: 'firstflutterapp-4ddae',
    storageBucket: 'firstflutterapp-4ddae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXEd46or7h-Tp9Vg2mqteV4jEhOX9zjsY',
    appId: '1:27868235925:ios:b3e1ef8ad9b7cd1b57f39c',
    messagingSenderId: '27868235925',
    projectId: 'firstflutterapp-4ddae',
    storageBucket: 'firstflutterapp-4ddae.firebasestorage.app',
    iosBundleId: 'com.example.fouthFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXEd46or7h-Tp9Vg2mqteV4jEhOX9zjsY',
    appId: '1:27868235925:ios:b3e1ef8ad9b7cd1b57f39c',
    messagingSenderId: '27868235925',
    projectId: 'firstflutterapp-4ddae',
    storageBucket: 'firstflutterapp-4ddae.firebasestorage.app',
    iosBundleId: 'com.example.fouthFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3HO5OZjuBaLssEVsfXXnSrrCx_DIGWqU',
    appId: '1:27868235925:web:0577f578b3d202f157f39c',
    messagingSenderId: '27868235925',
    projectId: 'firstflutterapp-4ddae',
    authDomain: 'firstflutterapp-4ddae.firebaseapp.com',
    storageBucket: 'firstflutterapp-4ddae.firebasestorage.app',
  );
}
