// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBC8iPHUKEHsk0S-Ez3Kz75UHqso6Rztk',
    appId: '1:883255451906:web:059242380c738784d4a21b',
    messagingSenderId: '883255451906',
    projectId: 'flutter-article-application',
    authDomain: 'flutter-article-application.firebaseapp.com',
    storageBucket: 'flutter-article-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNicSLtgopt9P9xhpXAfhFVjld2tMXGVk',
    appId: '1:883255451906:android:8abb16eed1932d64d4a21b',
    messagingSenderId: '883255451906',
    projectId: 'flutter-article-application',
    storageBucket: 'flutter-article-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYVaZ5rZy7QNU7Ira0So5BHIW34tPylmI',
    appId: '1:883255451906:ios:19eae01167d992f8d4a21b',
    messagingSenderId: '883255451906',
    projectId: 'flutter-article-application',
    storageBucket: 'flutter-article-application.firebasestorage.app',
    iosBundleId: 'com.example.fifthFlutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYVaZ5rZy7QNU7Ira0So5BHIW34tPylmI',
    appId: '1:883255451906:ios:19eae01167d992f8d4a21b',
    messagingSenderId: '883255451906',
    projectId: 'flutter-article-application',
    storageBucket: 'flutter-article-application.firebasestorage.app',
    iosBundleId: 'com.example.fifthFlutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBC8iPHUKEHsk0S-Ez3Kz75UHqso6Rztk',
    appId: '1:883255451906:web:707b055c09a30b8cd4a21b',
    messagingSenderId: '883255451906',
    projectId: 'flutter-article-application',
    authDomain: 'flutter-article-application.firebaseapp.com',
    storageBucket: 'flutter-article-application.firebasestorage.app',
  );
}
